CREATE DATABASE examen3;
USE examen3;

-- Especie
CREATE TABLE TBL_ESPECIE (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  NOMBRE_DESCUBIERTO VARCHAR(100) NOT NULL,
  FECHA DATETIME NOT NULL,
  TIPO VARCHAR(100) NOT NULL,
  GUID VARCHAR(100) NOT NULL
);