/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.componentes.controlexamen1;

/**
 *
 * @author Pablo
 */
public class PanelExamen1 extends javax.swing.JPanel {

    /**
     * Creates new form PanelExamen1
     */
    public PanelExamen1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sequenceTextArea = new javax.swing.JTextArea();
        pearsonCoefficientLabel = new javax.swing.JLabel();
        calculateBtn = new javax.swing.JButton();

        sequenceTextArea.setColumns(20);
        sequenceTextArea.setRows(5);
        sequenceTextArea.setToolTipText("");
        jScrollPane1.setViewportView(sequenceTextArea);

        pearsonCoefficientLabel.setText("Pearson Coefficient:");

        calculateBtn.setText("Calcular");
        calculateBtn.setActionCommand("Calculate");
        calculateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pearsonCoefficientLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(pearsonCoefficientLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calculateBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pearsonCoefficientLabel.getAccessibleContext().setAccessibleName("Pearson Coefficient:");
        pearsonCoefficientLabel.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calculateBtnMouseClicked
        String sequence = sequenceTextArea.getText();
        PearsonCoefficient pearsonCoefficient = new PearsonCoefficient(sequence);
        pearsonCoefficientLabel.setText("Pearson Coefficient: " + 
                String.format("%.4f", pearsonCoefficient.getPearsonCoefficient()));
    }//GEN-LAST:event_calculateBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pearsonCoefficientLabel;
    private javax.swing.JTextArea sequenceTextArea;
    // End of variables declaration//GEN-END:variables
}
