CREATE DATABASE examen2;
USE examen2;

-- Bodega
CREATE TABLE TBL_BODEGA (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL
);

INSERT INTO TBL_BODEGA (NOMBRE) VALUES
('Bodega #1'), ('Bodega #2'), ('Bodega #3'), ('Bodega #4');

-- Producto
CREATE TABLE TBL_PRODUCTO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  GRADO CHAR NOT NULL,
  CANTIDAD_TOTAL INT NOT NULL,
  CANTIDAD_CAJAS INT NOT NULL,
  INGRESO DATETIME NOT NULL,
  ID_BODEGA INT NOT NULL,
  CONSTRAINT `FK_BODEGA_PRODUCTO` FOREIGN KEY (ID_BODEGA) REFERENCES TBL_BODEGA (ID)
);